# Generated by Django 6.0.2 on 2026-02-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantmodel',
            name='resume',
            field=models.FileField(null=True, upload_to='media/applicant_resume'),
        ),
        migrations.AddField(
            model_name='applicantmodel',
            name='year_of_experience',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
